### ISSUE TITLE
ConnectionSet leak during failure

### ISSUE THREAD

**Issue by arekinath** [joyent/node-cueball#123]
When we have a ConnectionSet and a lot of failing backends, we can leak LogicalConnections -- they enter state "init" and then their FSM fails. They have no transition out of this state and nothing to remove them from the set's `cs_lconns` (this would normally happen if they transitioned to 'stopped'). These can leak and build up and carry a lot of references that eat memory.

**Comment by davepacheco** [comment]
See also: [MORAY-423](https://smartos.org/bugview/MORAY-423)
