### ISSUE TITLE
DNSResolver should retry at TTL if it's seen it

### ISSUE THREAD

**Issue by arekinath** [joyent/node-cueball#151]

**Comment by davepacheco** [comment]
CR: https://cr.joyent.us/#/c/5209/

I think this fix would have significantly helped in SCI-610 and SCI-682.

**Comment by arekinath** [comment]
Tested this patch by using cbresolve on a name in a local BIND. Set name's A record TTL to 70 sec, let the initial lookup succeed, then turned off the BIND. Observed how often timeouts were being logged and checked it was on a 70sec cycle not 60sec.
