### ISSUE TITLE
timers and sockets should not be unref'd

### ISSUE THREAD

**Issue by davepacheco** [joyent/node-cueball#26]
I want to write a command-line tool for a Cueball-based client (node-moray) that waits for a connection to be established, even if the remote server is in DNS or isn't listening on the given TCP port.  This is not the common case -- most of the CLI tools want to fail fast when servers are not available -- but it would be nice to have a mode where they could block until servers become available.  Right now, those programs instead exit 0 without having done anything.

I think this applies to resolvers, pools, and the upcoming sets.

I'd also be fine with never unref'ing timers and just requiring programs that want to exit to just have to call close().

**Comment by davepacheco** [comment]
This turns out to be a more serious issue because we have long-running (daemon-like) components that don't actually function as servers and so don't have listening sockets open.  But when Moray is unavailable, instead of continuing to retry, they exit normally.  See [MANTA-3090](http://smartos.org/bugview/MANTA-3090) for an example.

**Comment by arekinath** [comment]
I think what we do currently is actually just plain incorrect. We should never unref timers until we're past an initial success or failure.

This means that a Pool should not unref its slot's backoff timers unless the backend in question is already dead (so that if they're all dead we're in "failed" state and we've already failed the requests and notified the user appropriately). A Resolver should not unref its timers until it's either had a successful resolution or completely given up (*and* transitioned to "failed")

**Comment by trentm** [comment]
c.f. https://smartos.org/bugview/TOOLS-1642

**Comment by arekinath** [comment]
So minnow puts a spanner in the works here -- it's neither a command-line tool (which should exit once reaching "failed"), nor a server (which has a listening socket to keep it open). It wants to stay up indefinitely, but has nothing to serve.

Maybe what we should do here is actually stop unref'ing timers and sockets altogether, and make explicit in the API that commandline tools must call `pool.stop()` and similar functions upon entering `"failed"` if they want to exit the process. @trentm would this work for `sdcadm`? There's a `stop()` function on the `Agent` that could be used there.

**Comment by trentm** [comment]
@arekinath Yes an explicit `.stop()` or `.close()` is pretty typical for CLIs to have to use for things like this.  Sounds good to me.

**Comment by trentm** [comment]
https://cr.joyent.us/#/c/1434
