### ISSUE TITLE
want claim() to return in same event loop run if possible

### ISSUE THREAD

**Issue by arekinath** [joyent/node-cueball#66]
Currently claim() can only ever call the `cb` successfully in at least the next turn of the event loop. It would be nice if in the easy case (socket already available) it can return immediately.

**Comment by davepacheco** [comment]
Do you mean to call the callback synchronously in some cases and async in others?  I think that's generally considered an anti-pattern in Node.

**Comment by arekinath** [comment]
Yes, it is a bit of an anti-pattern, but it does shave ~5ms or so off the time it takes to get an HTTP request started with a cueball agent.

**Comment by jclulow** [comment]
I think if you're going to try and make the optimisation, you would want a synchronous function, e.g. `tryClaim()`, which could return `null` if the asynchronous version is required.

**Comment by arekinath** [comment]
We actually had a synchronous claim function in the original design that worked like that, but got rid of it because it's too easy to use incorrectly (if you just call it only and not the async claim() always if it fails, it ruins the back-pressure of queueing and the way rebalancing works). I'll abandon this idea.
